MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.01

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,39 +4,62 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
-    - CONDA_PY=34
-    - CONDA_PY=35
+    - CONFIG=osx_python2.7
+    - CONFIG=osx_python3.6
+    - CONFIG=osx_python3.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "BOkv2eDyueciOXf643bcUkCYZje8QuOOKxC+tJmI2yPWwqdUU74579LSnJuRsiY+6PuDL8QT4HBZis6x9kK3SQf/Cw5oaXEitIKTDepxLe2K6s+kvxXjXq+GvGJNa5wjzXWC9vT7j3eD7/N5w2D4EbjQ2r2pnlRlQPTeS2xdxVWTb8nPfKaOGls6jUp3fzgUdHPGw49oxgbhRggIoAzxQitt+wxLg3p3VF9inZ94q4fHbZY34EGiTEHCchk1io+5TawYG9za6kpRoQUoo574nX9mW8t1YN6yZ0FxNMP/lLy0B5sFYoo/4q/2YvN5Hi/0sUrp2aQ7G/D7V83fn4vOs3NPfXiqplW2vi1ytQYNG3Rmo+0ko5p0dKruY1JFHk9lsaaJgdrQKHHd1Wsj5IvnWpA8y00XEAiyikKMZDuwE01mlaKM3HR99M3wdwA1n68DYEcY5N0BtITSBVjupKPvVI44A9lbpvoxP2SHUO2raYg4XsRweAWSk+hpJsc2R8GYZzpq6UkvimkLHa1DCoo0nWExaaMl4F4MhHPevBtK25nuibYLw/FJT2hTUvufWxEuVUApVkfXxRmmYEa+zyM0YOQg0RlR95CHLt6wfbkMQbusFE9KbfJx0aQzouG8OgL2aJrz6u31mhc3l3j7xuqxra/Z4kXmtBh9Mn3HHBRPdpA="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
